spring:

  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: xyz.n490808114.shopWeb.dao
server:
  port: 8081